# Generated by Django 5.1.4 on 2025-01-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='5b1af', max_length=5, primary_key=True, serialize=False),
        ),
    ]
