# Generated by Django 5.1.4 on 2025-02-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0006_alter_loan_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='co_maker',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_maker_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_maker_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_maker_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='co_maker_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='6f136', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
