# Generated by Django 5.1.4 on 2025-02-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0007_loan_co_maker_loan_co_maker_2_loan_co_maker_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='0305a', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
