# Generated by Django 5.1.4 on 2025-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0009_alter_loan_control_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='original_principal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='d3716', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
