# Generated by Django 5.1.4 on 2025-02-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0010_paymentschedule_original_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='346d8', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
