# Generated by Django 5.1.4 on 2025-02-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0011_alter_loan_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='b8a45', max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
