# Generated by Django 5.1.4 on 2025-02-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0013_alter_loan_control_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='co_maker',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='co_maker_2',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='co_maker_3',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='co_maker_4',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='co_maker_5',
        ),
        migrations.RemoveField(
            model_name='paymentschedule',
            name='original_principal',
        ),
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='8f9ab', max_length=5, primary_key=True, serialize=False),
        ),
    ]
