# Generated by Django 5.1.4 on 2025-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcoop_app', '0015_loan_co_maker_loan_co_maker_2_loan_co_maker_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='control_number',
            field=models.CharField(default='0f270', max_length=5, primary_key=True, serialize=False),
        ),
    ]
